apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "flask-app-chart.name" . }}
  ports:
  - port: {{ .Values.service.port | default 8000 }}
    targetPort: {{ .Values.service.port | default 8000 }}
  type: ClusterIP
