# 全局名称覆盖
fullnameOverride: ""
nameOverride: ""

# 副本数
replicaCount: 6

# 镜像配置
image:
  repository: "mydockerregistry.com:5000/flask-app"
  tag: "1.0"
  pullPolicy: "IfNotPresent"
  pullSecrets:
    - my-registry-secret

# 资源限制
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# 环境变量
env:
  ENV_VAR_1: "value1"
  ENV_VAR_2: "value2"

# Ingress 配置
ingress:
  enabled: true
  host: "flask-app.example.com"
  path: "/foo(/|$)(.*)"
  pathType: "ImplementationSpecific"

# Service 配置
service:
  port: 8000

serviceAccount:
  create: false
  name: ""
  
autoscaling:
 enabled: false
